---
title: "HTT_AppliedStats_FinalProject_2025"
format: html
---
```{r}
# via Quarto: Ensure that the code used to generate markdown isn't included in the final output
#| echo: false
```

```{r}
# Load libraries
library(tidyverse)
library(dplyr)
library(purrr)
library(openxlsx)
library(ggplot2)
library(hms)
```

```{r}
# Set working directory in terminal
# setwd("C:/Users/mykal/OneDrive - The Pennsylvania State University/Grab Lab - Mykalas_Projects - Documents/Mykalas_Projects/projects/High Tunnel Thrips/analysis/HTT-AppliedStats/data")

# Load tomato thrips damage data from local environment
# replace with path to "TomatoThripsDamageRS.xlsx"
TomatoThripsDamageRS <- read.xlsx("C:/Users/mykal/OneDrive - The Pennsylvania State University/Grab Lab - Mykalas_Projects - Documents/Mykalas_Projects/projects/High Tunnel Thrips/analysis/HTT-AppliedStats/data/TomatoThripsDamageRS.xlsx", detectDates = TRUE)

# replace with path to "TomatoThripsDamageSEAREC.xlsx"
TomatoThripsDamageSEAREC <- read.xlsx("C:/Users/mykal/OneDrive - The Pennsylvania State University/Grab Lab - Mykalas_Projects - Documents/Mykalas_Projects/projects/High Tunnel Thrips/analysis/HTT-AppliedStats/data/TomatoThripsDamageSEAREC.xlsx", detectDates = TRUE)

# Load ground cover ID data from local environment
# replace with path to "Site_GroundCover_2025.xlsx"
GroundCoverID <- read.xlsx("C:/Users/mykal/OneDrive - The Pennsylvania State University/Grab Lab - Mykalas_Projects - Documents/Mykalas_Projects/projects/High Tunnel Thrips/analysis/HTT-AppliedStats/data/Site_GroundCover_2025.xlsx", detectDates = TRUE)

# Create data frame for tomato thrips damage `  for both RS and SEAREC sites
TomatoThripsDamage_raw <- bind_rows(TomatoThripsDamageRS, TomatoThripsDamageSEAREC)

# Change column name 'ground cover' to 'plot_ID'
TomatoThripsDamage_raw <- TomatoThripsDamage_raw %>%
  rename(plot_ID = ground_cover)
  
# Add 'ground_cover' column to combined data
TomatoThripsDamage_raw <- left_join(TomatoThripsDamage_raw, GroundCoverID, by = "plot_ID")

# Subset to remove redundant columns "X", "site.y", and "year"
TomatoThripsDamage <- subset(TomatoThripsDamage_raw, select= -c(X6, year, site.y))

# Rename column 'site.x' to 'site'
TomatoThripsDamage <- TomatoThripsDamage %>%
  rename(site = site.x) %>%
  # change grade and damage_rating to factors
  # add julian_day column
  mutate(grade = as.factor(grade), 
  damage_rating = as.factor(damage_rating)) %>%
  mutate(damage_rating = factor(damage_rating, levels = c("3", "2", "1", "0")),
    julian_day = yday(date)) %>%
  # create whole_plot and sub_plot from plot_ID
  mutate(whole_plot = case_when(
                        substr(plot_ID,1,1) == "A" ~ 1,
                        substr(plot_ID,1,1) == "B" ~ 1,
                        substr(plot_ID,1,1) == "C" ~ 1,
                        substr(plot_ID,1,1) == "G" ~ 1,
                        substr(plot_ID,1,1) == "H" ~ 1,
                        substr(plot_ID,1,1) == "I" ~ 1,
                        substr(plot_ID,1,1) == "D" ~ 2,
                        substr(plot_ID,1,1) == "E" ~ 2,
                        substr(plot_ID,1,1) == "F" ~ 2,
                        substr(plot_ID,1,1) == "J" ~ 2,
                        substr(plot_ID,1,1) == "K" ~ 2,
                        substr(plot_ID,1,1) == "L" ~ 2),
          sub_plot = case_when(
                        substr(plot_ID,1,1) == "A" ~ 1,
                        substr(plot_ID,1,1) == "D" ~ 1,
                        substr(plot_ID,1,1) == "G" ~ 1,
                        substr(plot_ID,1,1) == "J" ~ 1,
                        substr(plot_ID,1,1) == "B" ~ 2,
                        substr(plot_ID,1,1) == "E" ~ 2,
                        substr(plot_ID,1,1) == "H" ~ 2,
                        substr(plot_ID,1,1) == "K" ~ 2,
                        substr(plot_ID,1,1) == "C" ~ 3,
                        substr(plot_ID,1,1) == "F" ~ 3,
                        substr(plot_ID,1,1) == "I" ~ 3,
                        substr(plot_ID,1,1) == "L" ~ 3))


# Look at data
head(TomatoThripsDamage)
summary(TomatoThripsDamage)
```

```{r}
# Tidy temperature data
# path of directory
# Replace with path to where temperature .xlsx files are
temperature_directory <- "C:/Users/mykal/OneDrive - The Pennsylvania State University/Grab Lab - Mykalas_Projects - Documents/Mykalas_Projects/projects/High Tunnel Thrips/analysis/HTT-AppliedStats/data"

# List temperature files from local path 
temperature_list <- list.files(path = temperature_directory, pattern = "^temp_")

# Create data frame names for temp_list without ".xlsx" at end
temperature_names <- sub("\\.xlsx$", "", temperature_list)

# loop to read in excel files
for (i in temperature_names) {
  # set file path
  filepath <- file.path(path = temperature_directory, 
  paste(i, ".xlsx", sep = ""))
  # read each file and name it the file name
  assign(i, 
    read.xlsx(xlsxFile = filepath,
    startRow = 22,
    colNames = FALSE,
    detectDates = TRUE
    ))
}

## Tidy over multiple data frames
# Create list of temp dataframes
temperature_df_list <- mget(ls(.GlobalEnv, pattern = "^temp_"))

temperature_df_list_purrr <- map2( 
  # Defines list of data frames
  .x = temperature_df_list,
  # Defines list of strings that correspond to data fram names
  .y = temperature_names,
  # Defines function to apply -- must use parentheses before .x to get dplyr to work!!
  .f = ~ (.x %>%
    rename(date = X1,
    time = X2,
    temperature_c = X3,
    humidity_rh = X4) %>%
    mutate(date = as.Date(date), 
      time = hms::as_hms(time),
      temperature_c = as.numeric(temperature_c),
      humidity_rh = as.numeric(humidity_rh)) %>%
    # make sensor_ID column, named as file name
    mutate(sensor_ID = .y) %>%
    # Create columns from file name contents
    # add column for 'below' or 'above'
    # add column for site
    # add column for groundcover
    # add column for replacement
    separate(col = sensor_ID, into = c("temp", "site", "plot_ID_row", "sensor_placement", "replacement"), sep = "_") %>%
    # delete dummy temp column
    mutate(temp = NULL) %>%
    # make new columns plot_ID and row
    mutate(plot_ID = substr(plot_ID_row, 1,1), row = substr(plot_ID_row,2,2)) %>%
    # remove column plot_ID_row
    mutate(plot_ID_row = NULL) %>%
    # lubridate create date_time column as date-time data type
    mutate(date_time = ymd_hms(paste(date, time))) %>%
    # add julian_day column
    # assign 'day' and 'night' to 6AM-8PM for summer daylight coverage
    mutate(julian_day = yday(date),
      day_night = dplyr::case_when(
        between(time, hms::as_hms("06:00:00"), hms::as_hms("20:00:00")) ~ "daytime",
        TRUE ~ "nighttime")
      ) %>%
    # create whole_plot and sub_plot from plot_ID
     mutate(whole_plot = case_when(
                        substr(plot_ID,1,1) == "A" ~ 1,
                        substr(plot_ID,1,1) == "B" ~ 1,
                        substr(plot_ID,1,1) == "C" ~ 1,
                        substr(plot_ID,1,1) == "G" ~ 1,
                        substr(plot_ID,1,1) == "H" ~ 1,
                        substr(plot_ID,1,1) == "I" ~ 1,
                        substr(plot_ID,1,1) == "D" ~ 2,
                        substr(plot_ID,1,1) == "E" ~ 2,
                        substr(plot_ID,1,1) == "F" ~ 2,
                        substr(plot_ID,1,1) == "J" ~ 2,
                        substr(plot_ID,1,1) == "K" ~ 2,
                        substr(plot_ID,1,1) == "L" ~ 2),
          sub_plot = case_when(
                        substr(plot_ID,1,1) == "A" ~ 1,
                        substr(plot_ID,1,1) == "D" ~ 1,
                        substr(plot_ID,1,1) == "G" ~ 1,
                        substr(plot_ID,1,1) == "J" ~ 1,
                        substr(plot_ID,1,1) == "B" ~ 2,
                        substr(plot_ID,1,1) == "E" ~ 2,
                        substr(plot_ID,1,1) == "H" ~ 2,
                        substr(plot_ID,1,1) == "K" ~ 2,
                        substr(plot_ID,1,1) == "C" ~ 3,
                        substr(plot_ID,1,1) == "F" ~ 3,
                        substr(plot_ID,1,1) == "I" ~ 3,
                        substr(plot_ID,1,1) == "L" ~ 3))
  )
)


# update changes to dataframe list in the global environment
list2env(temperature_df_list_purrr, .GlobalEnv)

# make df_list into combined dataframe
Temperature_raw <- bind_rows(temperature_df_list_purrr, .id = "column_label") %>%
    rename(sensor_ID = column_label)

# add ground cover to temp sensor data by plot_ID
Temperature <- Temperature_raw %>%
  left_join(GroundCoverID %>%
   dplyr::select(ground_cover, plot_ID), by = "plot_ID")

# Aggregate data frame for mean temperature_c 
Temperature.agg <- Temperature %>%
  group_by(julian_day, site, sensor_placement, ground_cover, plot_ID, whole_plot, sub_plot, day_night) %>%
  summarize(mean_temperature_c = mean(temperature_c, na.rm = TRUE))

# Temperature subsets for above- and below-ground
# Above-ground
Temperature_above <- Temperature.agg %>%
  subset(sensor_placement == "a")
# Below-ground
Temperature_below <- Temperature.agg %>%
  subset(sensor_placement == "b")


## by site and above/below ground 
## RS
# Above-ground
Temperature_above_RS <- Temperature.agg %>%
  subset(sensor_placement == "a" & site == "RS")
# Below-ground
Temperature_below_RS <- Temperature.agg %>%
  subset(sensor_placement == "b" & site == "RS")

## SEAREC
# Above-ground
Temperature_above_SEAREC <- Temperature.agg %>%
  subset(sensor_placement == "a" & site == "SEAREC")
# Below-ground
Temperature_below_SEAREC <- Temperature.agg %>%
  subset(sensor_placement == "b" & site == "SEAREC")

```

```{r}
# Load libraries
library(sjPlot)
library(nnet)
library(lme4)
library(lmerTest)


## Finally time for analysis!

############ Thrips Damage ##############
## Research question: Is thrips damage severity on tomato fruits impacted by ground cover type in high tunnel tomatoes?
# Null hypothesis: Thrips damage severity does not differ across ground cover type.
# Response variable: damage severity (categorical-ordinal/nominal)
# Fixed effects
# Predictor variable: ground cover (categorical-discrete)
# Other predictor variables:  site (categorical-nominal), julian_day(numerical-continuous)
# Random effects
# variable: sub_plot (replications of ground cover)
# Data: TomatoThripsDamage

## Look at raw data first
ggplot(data = TomatoThripsDamage, aes(x = ground_cover, y = damage_rating, color = site)) +
  geom_jitter() +
  facet_wrap(~site)

# labellers
severity_colors <- c("0" = "#785EF0", "1" = "#DC267F", "2"= "#FE6100", "3" = "#FFB000")
severity_labels <- c("0" = "None", "1" = "Mild", "2"= "Moderate", "3" = "Severe")
ground_cover_labels <- c("fabric" = "Fabric", "soil" = "Soil", "straw" = "Straw")

# Damage severity by ground cover raw
ggplot(TomatoThripsDamage, aes(x = ground_cover, fill = damage_rating)) +
  geom_histogram(stat = "count") +
  facet_wrap(~site) +
  labs(x = "Ground Cover", y = "Fruit Count", fill = "Damage Severity", title = "Thrips Damage Severity in Tomato Fruits") +
  scale_fill_manual(values = severity_colors, labels = severity_labels) +
  scale_x_discrete(labels = ground_cover_labels) +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=15),
        plot.title=element_text(size=15, face="bold"),
        legend.title=element_text(size=13),
        legend.text=element_text(size=12),
        strip.text=element_text(size=13))


# damage severity over time facet wrapped by ground cover and site
ggplot(TomatoThripsDamage, aes(x = date, color = damage_rating)) +
  geom_line(stat = "count") + 
  facet_grid(site ~ ground_cover) +
  labs(x = "Date", y = "Fruit Count", color = "Damage Severity") +
  scale_color_manual(values = severity_colors, labels = severity_labels)

## Proposed model
# damage~site*ground_cover*date

## Multinomial logisitic regression
## multinom package does not include p-value calculation for the regression coefficients
## p-values calculated using Wald tests
## Model per site since site has a large effect (remove site from model), and no '0' occur at SEAREC

# Rock Springs(RS) model
# subset damage data for only Rock Springs
TomatoThripsDamage_RS <- TomatoThripsDamage %>%
  subset(site == "RS")

# establish baseline at lowest level of damage
TomatoThripsDamage_RS$damage_rating_baseline <- relevel(TomatoThripsDamage_RS$damage_rating, ref = "0")

# build multinomial model
# multinomial logistic regression model
# response variable: damage_rating_baseline -- all comparisons are the log odds
# of observing the alternative ratings compared to the baseline (no damage)
# damage rating baseline values and meanings: 
# "1" : 0(no damage)-1(mild) damage severity
# "2" : 0(none)-2(moderate) damage severity
# "3" : 0(none)-3(severe) damage severity

multinom_RS <- multinom(damage_rating_baseline~ground_cover+julian_day, data = TomatoThripsDamage_RS)
summary(multinom_RS)
# summary output of model
# multinom(formula = damage_rating_baseline ~ ground_cover + julian_day, 
#    data = TomatoThripsDamage_RS)
#
# Coefficients:
#  (Intercept)(fab) ground_coversoil ground_coverstraw   julian_day
# 3  0.07779539       -1.2312957         1.0859055 -0.002314783
# 2 -3.16612327       -1.4333166        -0.2475973  0.019159073
# 1 -8.20775576       -0.7052384         0.2034775  0.043648388
# 
# Std. Errors:
#   (Intercept)(fab) ground_coversoil ground_coverstraw  julian_day
# 3    2.116065        0.9569941         0.7338957 0.009138576
# 2    1.995059        0.5823043         0.5849226 0.008414835
# 1    1.695507        0.5036447         0.5439638 0.007155085
# 
# Residual Deviance: 611.331 
# AIC: 635.331

# HTML table output of model
tab_model(multinom_RS,
           transform = NULL, 
           show.est = TRUE, 
           show.se = TRUE,
          show.stat = TRUE,
          show.df = TRUE,
          show.ci = FALSE,
          col.order = c("est", "se", "stat", "df.error", "response.level", "p"),
           title = "Multinominal Logistic Regression Summary for Rock Springs",
           string.se = "SE",
           p.style = "numeric",
           string.ci = "CI (95%)",
           string.pred = "Coefficient",
           string.p = "p-value",
          string.stat = "Z Statistic",
           digits = 3,
           dv.labels = "Damage Rating (baseline)",
           pred.labels = c(
            "Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day",
            "Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day",
            "Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day"
           )
           )



# interpretations of coefficients (effect size)
# example:  A one-unit increase in the variable write is associated with the decrease in the log odds of being in general program vs. academic program in the amount of .058 .

# calculate p values using two-tailed z-tests
z <- summary(multinom_RS)$coefficients/summary(multinom_RS)$standard.errors
z
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
# p output
#    (Intercept)(fab) ground_coversoil ground_coverstraw   julian_day
# 3   9.706730e-01       0.19822388         0.1389679     8.000380e-01
# 2   1.125166e-01       0.01383743         0.6720770     2.279692e-02
# 1   1.292609e-06       0.16143258         0.7083564     1.058490e-09

# interpretation of p value table
# For 0-1, significant predictors: fabric ground cover and julian day
# For 0-2, significant predictors: soil ground cover and julian day
# For 0-3, significant predictors: no significant predictors


# relative risk (or odds): the ratio of the probability of choosing one alternative outcome over the probability of choosing the baseline; the right-hand side linear equation exponentiated, meaning the exponentiated regression coefficients are relative risk rations for a unit change in the predictor variable
# exponentiated model coefficients
relriskRS <- as.data.frame(exp(coef(multinom_RS)))
#    (Intercept) ground_coversoil ground_coverstraw julian_day
# 3 1.0809014770        0.2919141         2.9621208  0.9976879
# 2 0.0421667504        0.2385166         0.7806743  1.0193438
# 1 0.0002725317        0.4939908         1.2256575  1.0446150

# relative risk data frame as nice HTML table
tab_df(relriskRS,
       show.rownames = TRUE,
        title = "Relative Risk Ratio (Exponentiated Model Coefficients)",
        col.header = c("Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day"),
            digits = 4,   
        )

# this model lacks comparisons between alternative ratings (ie. 1-2,2-3, or 1-3)
# So this model shows the likelihood of observing each damage severity compared to no damage
# but I think that's okay because I'm not sure its valuable to know the likelihood
# of moving between damage severity ratings


## repeat multinomial regression for SEAREC
# SEAREC model
# subset damage data for only Rock Springs
TomatoThripsDamage_SEAREC <- TomatoThripsDamage %>%
  subset(site == "SEAREC")

# establish baseline at lowest level of damage
# putting baseline at "1" since there were no "0" ratings at SEAREC
TomatoThripsDamage_SEAREC$damage_rating_baseline <- relevel(TomatoThripsDamage_SEAREC$damage_rating, ref = "1")


#multinomial logistic regression model
multinom_SEAREC <- multinom(damage_rating_baseline~ground_cover+julian_day, data = TomatoThripsDamage_SEAREC)
summary(multinom_SEAREC)
# multinom(formula = damage_rating_baseline ~ ground_cover + julian_day, 
#    data = TomatoThripsDamage_SEAREC)
#
# Coefficients:
#   (Intercept) ground_coversoil ground_coverstraw  julian_day
# 3    8.677377       -0.5220642         0.8218130 -0.03821138
# 2    9.151975       -0.7835137         0.8720271 -0.03676121
# 
# Std. Errors:
#   (Intercept) ground_coversoil ground_coverstraw  julian_day
# 3    2.436728        0.3873535         0.3981148 0.009931555
# 2    1.983107        0.3166285         0.3295557 0.008019830
# 
# Residual Deviance: 637.4579
# AIC: 653.4579

# nice HTML table of model output
tab_model(multinom_SEAREC,
           transform = NULL, 
           show.est = TRUE, 
           show.se = TRUE,
          show.stat = TRUE,
          show.df = TRUE,
          show.ci = FALSE,
          col.order = c("est", "se", "stat", "df.error", "response.level", "p"),
           title = "Multinominal Logistic Regression Summary for SEAREC",
           string.se = "SE",
           p.style = "numeric",
           string.ci = "CI (95%)",
           string.pred = "Coefficient",
          string.stat = "Z Statistic",
           string.p = "p-value",
           digits = 3,
           dv.labels = "Damage Rating (baseline)",
           pred.labels = c(
            "Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day",
            "Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day"
           )
           )

z <- summary(multinom_SEAREC)$coefficients/summary(multinom_SEAREC)$standard.errors
z
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
#    (Intercept) ground_coversoil ground_coverstraw   julian_day
# 3 3.693369e-04       0.17773169       0.038992924 1.193430e-04
# 2 3.931580e-06       0.01334034       0.008143323 4.566245e-06

# interpretation of p value table
# For 1-3, significant predictors: fabric ground cover and julian day
# For 1-2, significant predictors: fabric ground cover, soil ground cover, straw ground cover, and julian day

# relative risk ratios
relriskSEAREC <- as.data.frame(exp(coef(multinom_SEAREC)))
#   (Intercept) ground_coversoil ground_coverstraw julian_day
# 3    5868.634        0.5932946          2.274620  0.9625095
# 2    9433.051        0.4567981          2.391754  0.9639063

## correct for centered julian day to have interpretable intercept values

# Calculate the mean of the Julian day
mean_jd <- mean(TomatoThripsDamage_SEAREC$julian_day)

# Create a centered Julian day variable
TomatoThripsDamage_SEAREC$julian_day_centered <- TomatoThripsDamage_SEAREC$julian_day - mean_jd

# Rerun the model with the centered variable
multinom_SEAREC_centered <- multinom(
    formula = damage_rating_baseline ~ ground_cover + julian_day_centered, 
    data = TomatoThripsDamage_SEAREC
)

# Recalculate the RRRs
centered_rrr_values <- as.data.frame(exp(coef(multinom_SEAREC_centered)))

print(centered_rrr_values)

# relative risk data frame as nice HTML table
tab_df(centered_rrr_values,
       show.rownames = TRUE,
        title = "Relative Risk Ratio (Exponentiated Model Coefficients)",
        col.header = c("Ground Cover (Fabric)",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day"),
            digits = 4,   
        )




####### Temperature ##########
## Research question: Is above- or below-ground temperature impacted by ground cover type in high-tunnel tomatoes?
# Null hypothesis: Average temperature (below or above ground) does not differ across ground cover type. 
# Proposed model
# temperature~site*sensor_placement*ground_cover*julian_day


# labellers
ground_cover_colors <- c("fabric" = "#648FFF", "straw" = "#DC267F","soil"= "#FE6100")
ground_cover_labels <- c("fabric" = "Fabric", "soil" = "Soil", "straw" = "Straw")


# Look at data first
ggplot(data = Temperature, aes(x = sensor_placement, y = temperature_c, color = ground_cover)) +
  geom_boxplot() +
  stat_summary(fun = "mean") +
  facet_wrap(~site)

# raw temp data
hist(Temperature$temperature_c)
# looks pretty normal!
qqnorm(Temperature$temperature_c)
qqline(Temperature$temperature_c)
# these don't look great

# Look at aggregate data mean temp
ggplot(data = Temperature.agg, aes(x = sensor_placement, y = mean_temperature_c, color = ground_cover)) +
  geom_boxplot() +
  facet_wrap(~site)

# mean temp data
hist(Temperature.agg$mean_temperature_c)
qqnorm(Temperature.agg$mean_temperature_c)
qqline(Temperature.agg$mean_temperature_c)

hist(Temperature_above$mean_temperature_c)
hist(Temperature_below$mean_temperature_c)


# Look at aggregate data mean temp with day_night
ggplot(data = Temperature.agg, aes(x = sensor_placement, y = mean_temperature_c, color = ground_cover)) +
  geom_boxplot() +
  facet_grid(day_night~site)

ggplot(data = Temperature.agg, aes(x = sensor_placement, y = mean_temperature_c, color = ground_cover)) +
geom_boxplot() +
facet_grid(day_night~site)

ggplot(data = Temperature.agg, aes(mean_temperature_c, color = ground_cover)) +
geom_histogram() +
facet_grid(day_night~site+ground_cover)


ggplot(data = Temperature.agg, aes(mean_temperature_c, fill = ground_cover)) +
geom_density(alpha=.6) +
facet_grid(day_night~site)


###### two models above and below ground
# above
# needs transformation
### find way to reduce model bias, increase model complexity
t_above <- lmer(mean_temperature_c~site*ground_cover*julian_day*day_night+ (1|sub_plot), data = Temperature_above)
summary(t_above)

ggplot(Temperature_above, aes(x=julian_day, y=mean_temperature_c))+
geom_point()


sqrt(mean(Temperature_above$mean_temperature_c))
var(Temperature_above$mean_temperature_c)
# look at residuals
plot(residuals(t_above))

## try separated by site
## mixed model with subplot as a random effect
# no sensors above ground on fabric ground cover
mixed <- lmer(mean_temperature_c~ground_cover*julian_day*day_night+ (1|sub_plot), data = Temperature_above_RS)
summary(mixed)

#anova
anova(mixed)
#sig differences between groups in julian_day and day_night
# sig interaction term with julian_day and day_night
# no sig differences between ground cover

# Estimate the slope of 'julian_day' for each level of 'day_night'
trends_output <- emtrends(
  object = mixed, 
  specs = ~ day_night, 
  var = "julian_day"
)
comparison_of_slopes <- pairs(trends_output)
# barely significant, but not enough to be concerning


#not good
plot(residuals(mixed))
plot(mixed)
# seems like temporal autocorrelation

# pretty table HTML of model output
tab_model(mixed,
           transform = NULL, 
           show.est = TRUE, 
           show.se = TRUE,
          show.df = TRUE,
          show.stat = TRUE,
          col.order = c("est", "se", "ci", "stat", "df.error", "p"),
           title = "Mixed Linear Model Summary for Rock Springs",
           string.se = "SE",
           p.style = "numeric",
           string.ci = "CI (95%)",
          string.df = "DF",
           string.pred = "Coefficient",
           string.p = "p-value",
          string.stat = "T Statistic",
           digits = 3,
           dv.labels = "Above-Ground Mean Temperature (C)",
            pred.labels = c(
            "Intercept",
            "Ground Cover (Straw)",
            "Julian Day",
            "Day/Night (Nighttime)",
            "Ground Cover (Straw) x Julian Day",
            "Ground Cover (Straw) x Day/Night (Nighttime)",
            "Julian Day x Day/Night (Nighttime)",
            "Ground Cover (Straw) x Julian Day x Day/Night (Nighttime)"
           )
           )

# model visualization
    plot_model(
  model = mixed,
  type = "pred",
  terms = c("julian_day", "ground_cover", "day_night"),
  show.scatter = TRUE
)

# data visualization
ggplot(data = Temperature_above_RS, aes(x=julian_day, y=mean_temperature_c, color = ground_cover)) +
geom_line() +
facet_grid(~day_night)

# Mean temp by ground cover raw
ggplot(Temperature_above_RS, aes(x = julian_day, y = mean_temperature_c, color = ground_cover)) +
  geom_jitter(alpha=0.30) +
  geom_smooth(se=FALSE) +
  facet_wrap(~day_night, labeller = as_labeller(c(daytime = "Daytime", nighttime = "Nighttime"))) +
  labs(x = "Julian Day", y = "Mean Temperature (C)", color = "Ground Cover", title = "Mean Above-Ground Temperature (C) at Rock Springs") +
  scale_color_manual(values = c("straw" = "#DC267F","soil"= "#FE6100"), labels = c("soil" = "Soil", "straw" = "Straw"))+
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=15),
        plot.title=element_text(size=15, face="bold"),
        legend.title=element_text(size=13),
        legend.text=element_text(size=12),
        strip.text=element_text(size=15),
        strip.background = element_rect(fill = "#E9E9E9"),
        panel.background = element_rect(fill = "#F4F4F4"))


## repeat for below ground RS
## mixed model with subplot as a random effect
mixed <- lmer(mean_temperature_c~ground_cover*day_night*julian_day+ (1|sub_plot), data = Temperature_below_RS)
summary(mixed)

#anova
anova(mixed)
# sig difference between groups in ground_cover, day_night
# sig interaction terms of ground_cover:day_night, day_night:julian_day, 3 way interaction

# pretty table HTML of model output
tab_model(mixed,
           transform = NULL, 
           show.est = TRUE, 
           show.se = TRUE,
          show.df = TRUE,
          show.stat = TRUE,
          col.order = c("est", "se", "ci", "stat", "df.error", "p"),
           title = "Mixed Linear Model Summary for Rock Springs",
           string.se = "SE",
           p.style = "numeric",
           string.ci = "CI (95%)",
           string.pred = "Coefficient",
           string.p = "p-value",
          string.stat = "T Statistic",
          string.df = "DF",
           digits = 3,
           dv.labels = "Below-Ground Mean Temperature (C)",
           pred.labels = c(
            "Intercept",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Day/Night (Nighttime)",
            "Julian Day",
            "Ground Cover (Soil) x Day/Night (Nighttime)",
            "Ground Cover (Straw) x Day/Night (Nighttime)",
            "Ground Cover (Soil) x Julian Day",
            "Ground Cover (Straw) x Julian Day",
            "Julian Day x Day/Night (Nighttime)",
            "Ground Cover (Soil) x Day/Night (Nighttime) x Julian Day",
            "Ground Cover (Straw) x Day/Night (Nighttime) x Julian Day"
           )
           )


# model visualization
    plot_model(
  model = mixed,
  type = "pred",
  terms = c("julian_day", "ground_cover", "day_night"),
  show.scatter = TRUE
)

## post-hoc pairwise for interactions
# Estimate the slope of 'julian_day' for each level of 'day_night'
trends_output <- emtrends(
  object = mixed, 
  specs = ~ day_night, 
  var = "julian_day"
)
comparison_of_slopes <- pairs(trends_output)
#  contrast            estimate      SE   df t.ratio p.value
# daytime - nighttime   -0.022 0.00618 1287  -3.563  0.0004
#
# Results are averaged over the levels of: ground_cover 
# Degrees-of-freedom method: kenward-roger

# Estimate the marginal means for interaction
emm_means <- emmeans(
  object = mixed, 
  specs = ~ ground_cover * day_night
)

# Compare the ground covers within each day_night
pairs(emm_means, by = "day_night") 
# day_night = daytime:
# contrast       estimate    SE      df t.ratio p.value
# fabric - soil    0.6040 0.392 1286.95   1.541  0.2723
# fabric - straw   6.3784 0.992    1.20   6.428     NaN
# soil - straw     5.7744 0.999    1.23   5.779     NaN
#
# day_night = nighttime:
# contrast       estimate    SE      df t.ratio p.value
# fabric - soil    0.9520 0.392 1286.95   2.428  0.0405
# fabric - straw   0.9053 0.992    1.20   0.912     NaN
# soil - straw    -0.0467 0.999    1.23  -0.047     NaN
#
#Degrees-of-freedom method: kenward-roger 
#P value adjustment: tukey method for comparing a family of 3 estimates 



# Estimate the slope of julian_day for every unique combination of the other two factors
emm_3way_trends <- emtrends(
  object = mixed,
  specs = pairwise ~ day_night | ground_cover, # Compare day/night slopes within each ground cover
  var = "julian_day"
)

# View all comparisons
print(emm_3way_trends)
#$emtrends
#ground_cover = fabric:
# day_night julian_day.trend      SE   df lower.CL upper.CL
# daytime           -0.03286 0.00734 1288 -0.04725  -0.0185
# nighttime          0.01928 0.00734 1288  0.00489   0.0337
#
#ground_cover = soil:
# day_night julian_day.trend      SE   df lower.CL upper.CL
# daytime            0.00763 0.00793 1278 -0.00793   0.0232
# nighttime         -0.00104 0.00793 1278 -0.01661   0.0145
#
#ground_cover = straw:
# day_night julian_day.trend      SE   df lower.CL upper.CL
# daytime           -0.00229 0.00772 1287 -0.01742   0.0129
# nighttime          0.02031 0.00772 1287  0.00518   0.0355
#
#Degrees-of-freedom method: kenward-roger 
#Confidence level used: 0.95 
#
#$contrasts
#ground_cover = fabric:
# contrast            estimate     SE   df t.ratio p.value
# daytime - nighttime -0.05214 0.0103 1287  -5.072  <.0001
#
#ground_cover = soil:
# contrast            estimate     SE   df t.ratio p.value
# daytime - nighttime  0.00868 0.0109 1287   0.795  0.4266

#ground_cover = straw:
# contrast            estimate     SE   df t.ratio p.value
# daytime - nighttime -0.02260 0.0109 1287  -2.071  0.0385

# make table of post-hoc contrasts
trends_df <- as_tibble(emm_3way_trends$contrasts)
  
    trends_table <- trends_df %>%
      select(ground_cover, contrast, estimate, SE, df, t.ratio, p.value) %>%
      rename(
        `Ground Cover` = ground_cover,
        `Contrast (Daytime - Nighttime)` = contrast,
        `Estimate (Slope Difference)` = estimate,
        `SE` = SE,
        `df` = df,
        `t Ratio` = t.ratio,
        `p-value` = p.value
      )

tab_df(trends_df,
       col.header = c("Contrast", "Ground Cover", "Estimate", "SE", "DF", "T Ratio", "P Value"),
       digits = 7,
       p.style = "numeric"
       )


# data visualization
ggplot(data = Temperature_below_RS, aes(x=julian_day, y=mean_temperature_c, color= ground_cover)) +
geom_line()+
facet_wrap(~day_night)

# fig for paper
ggplot(data = Temperature_below_RS, aes(x = julian_day, y = mean_temperature_c, color = ground_cover)) +
  geom_jitter(alpha=0.30) +
  geom_smooth(se=FALSE) +
  facet_wrap(~day_night, labeller = as_labeller(c(daytime = "Daytime", nighttime = "Nighttime"))) +
  labs(x = "Julian Day", y = "Mean Temperature (C)", color = "Ground Cover", title = "Mean Below-Ground Temperature (C) at Rock Springs") +
  scale_color_manual(values = ground_cover_colors, labels = ground_cover_labels)+
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=15),
        plot.title=element_text(size=15, face="bold"),
        legend.title=element_text(size=13),
        legend.text=element_text(size=12),
        strip.text=element_text(size=15),
        strip.background = element_rect(fill = "#E9E9E9"),
        panel.background = element_rect(fill = "#F4F4F4"))

### SEAREC
# above ground
## mixed model with subplot as a random effect
## shorter date coverage to match short sensor logging
mixed <- lmer(mean_temperature_c~ground_cover*julian_day*day_night+ (1|sub_plot), data = Temperature_above_SEAREC  %>% filter(julian_day<226))
summary(mixed)

#anova
anova(mixed)
# sig difference between groups for julian_day and day_night
# no sig interactions



# pretty table HTML of model output
tab_model(mixed,
           transform = NULL, 
           show.est = TRUE, 
           show.se = TRUE,
          show.df = TRUE, 
          show.stat = TRUE,
          col.order = c("est", "se", "ci", "stat", "df.error", "p"),
           title = "Mixed Linear Model Summary for SEAREC",
           string.se = "SE",
           p.style = "numeric",
           string.ci = "CI (95%)",
           string.pred = "Coefficient",
          string.stat = "T Statistic",
           string.p = "p-value",
          string.df = "DF",
           digits = 3,
           dv.labels = "Above-Ground Mean Temperature (C)",
           pred.labels = c(
            "Intercept",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day",
            "Day/Night (Nighttime)",
            "Ground Cover (Soil) x Julian Day",
            "Ground Cover (Straw) x Julian Day",
            "Ground Cover (Soil) x Day/Night (Nighttime)",
            "Ground Cover (Straw) x Day/Night (Nighttime)",
            "Julian Day x Day/Night (Nighttime)",
            "Ground Cover (Soil) x Day/Night (Nighttime) x Julian Day",
            "Ground Cover (Straw) x Day/Night (Nighttime) x Julian Day"
           )
           )

# model visualization
    plot_model(
  model = mixed,
  type = "pred",
  terms = c("julian_day", "ground_cover", "day_night"),
  show.scatter = TRUE
)

# data visualization
ggplot(data = Temperature_above_SEAREC, aes(x=julian_day, y=mean_temperature_c, color = ground_cover, linetype=plot_ID)) +
geom_line() +
facet_grid(~day_night)

# filtered julian day to match model
ggplot(data = Temperature_above_SEAREC  %>% filter(julian_day<226), aes(x=julian_day, y=mean_temperature_c, color = ground_cover, linetype=plot_ID)) +
geom_line() +
facet_grid(~day_night)

# fig for paper
ggplot(data = Temperature_above_SEAREC  %>% filter(julian_day<226), aes(x = julian_day, y = mean_temperature_c, color = ground_cover)) +
  geom_jitter(alpha=0.30) +
  geom_smooth(se=FALSE) +
  facet_wrap(~day_night, labeller = as_labeller(c(daytime = "Daytime", nighttime = "Nighttime"))) +
  labs(x = "Julian Day", y = "Mean Temperature (C)", color = "Ground Cover", title = "Mean Above-Ground Temperature (C) at SEAREC") +
  scale_color_manual(values = ground_cover_colors, labels = ground_cover_labels)+
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=15),
        plot.title=element_text(size=15, face="bold"),
        legend.title=element_text(size=13),
        legend.text=element_text(size=12),
        strip.text=element_text(size=15),
        strip.background = element_rect(fill = "#E9E9E9"),
        panel.background = element_rect(fill = "#F4F4F4"))


# below ground SEAREC
## mixed model with subplot as a random effect
## filtered to account for sensor dying early
mixed <- lmer(mean_temperature_c~ground_cover*julian_day*day_night+ (1|sub_plot), data = Temperature_below_SEAREC %>% filter(julian_day<237))
summary(mixed)

#anova
anova(mixed)
# sig differences between groups in ground_cover, julian_day, day_night
# sig interaction terms of ground_cover:day_night, julian_day:day_night


# pretty table HTML of model output
tab_model(mixed,
           transform = NULL, 
           show.est = TRUE, 
           show.se = TRUE,
          show.stat = TRUE,
          show.df = TRUE,
          col.order = c("est", "se", "ci", "stat", "df.error", "p"),
           title = "Mixed Linear Model Summary for SEAREC",
           string.se = "SE",
           p.style = "numeric",
           string.ci = "CI (95%)",
           string.pred = "Coefficient",
           string.p = "p-value",
          string.df = "DF",
          string.stat = "T Statistic",
           digits = 3,
           dv.labels = "Below-Ground Mean Temperature (C)",
           pred.labels = c(
            "Intercept",
            "Ground Cover (Soil)",
            "Ground Cover (Straw)",
            "Julian Day",
            "Day/Night (Nighttime)",
            "Ground Cover (Soil) x Julian Day",
            "Ground Cover (Straw) x Julian Day",
            "Ground Cover (Soil) x Day/Night (Nighttime)",
            "Ground Cover (Straw) x Day/Night (Nighttime)",
            "Julian Day x Day/Night (Nighttime)",
            "Ground Cover (Soil) x Day/Night (Nighttime) x Julian Day",
            "Ground Cover (Straw) x Day/Night (Nighttime) x Julian Day"
           )
           )

# model visualization
    plot_model(
  model = mixed,
  type = "pred",
  terms = c("julian_day", "ground_cover", "day_night"),
  show.scatter = TRUE
)


# post hoc analysis of interaction terms  
# ground_cover:day_night
# Estimate marginal means for the interaction
emm_means_interaction1 <- emmeans(
  object = mixed, 
  specs = ~ ground_cover * day_night
)

# compare ground covers within each day_night level
pairs(emm_means_interaction1, by = "day_night")

# julian_day:day_night
# Estimate the slope of 'julian_day' for each level of 'day_night'
trends_output <- emtrends(
  object = mixed, 
  specs = ~ day_night, 
  var = "julian_day"
)
comparison_of_slopes <- pairs(trends_output)

# table
tab_df(as.data.frame(comparison_of_slopes),
       digits = 4)



tab_df(trends_df,
       col.header = c("Contrast", "Ground Cover", "Estimate", "SE", "DF", "T Ratio", "P Value"),
       digits = 7,
       p.style = "numeric"
       )
    
# data visualization raw
ggplot(data = Temperature_below_SEAREC, aes(x=julian_day, y=mean_temperature_c, color = ground_cover, linetype=plot_ID)) +
geom_line() +
facet_grid(~day_night)

# filtered for julian day same as model
ggplot(data = Temperature_below_SEAREC %>% filter(julian_day<237), aes(x=julian_day, y=mean_temperature_c, color = ground_cover)) +
geom_line() +
facet_grid(~day_night)

# fig for paper
ggplot(data = Temperature_below_SEAREC %>% filter(julian_day<237), aes(x = julian_day, y = mean_temperature_c, color = ground_cover)) +
  geom_jitter(alpha=0.30) +
  geom_smooth(se=FALSE) +
  facet_wrap(~day_night, labeller = as_labeller(c(daytime = "Daytime", nighttime = "Nighttime"))) +
  labs(x = "Julian Day", y = "Mean Temperature (C)", color = "Ground Cover", title = "Mean Below-Ground Temperature (C) at SEAREC") +
  scale_color_manual(values = ground_cover_colors, labels = ground_cover_labels)+
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=15),
        plot.title=element_text(size=15, face="bold"),
        legend.title=element_text(size=13),
        legend.text=element_text(size=12),
        strip.text=element_text(size=15),
        strip.background = element_rect(fill = "#E9E9E9"),
        panel.background = element_rect(fill = "#F4F4F4"))




```